version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
      - ./.env.local
    depends_on:
      - db

  db:
    restart: always
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env.local
    ports:
      - "54322:5432"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.http.routers.nginx.rule=Host(`flatrent.localhost`)"

  reverse-proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
