POST http://flatrent.localhost/api/flats HTTP/1.1
Content-Type: application/json

{
  "id": "01HPT4MRMGQ808WHWCX889XVAD",
  "address": {
    "city": "Rzeszów",
    "street": "Warszawska",
    "zipCde": "35-233",
    "building": {
      "number": 997,
      "doorNumber": 25,
      "flatNumber": 6
    }
  },
  "rooms": [
    {
      "id": "01HPWKVGYAFYBW71KQ84M0ZBR6",
      "roomName": "kuchnia",
      "roomType": "KITCHEN"
    },
    {
      "id": "01HPWKXDQC6M3SC8JJ68QBGX6S",
      "roomName": "lazienka",
      "roomType": "KITCHEN"
    },
    {
      "id": "01HPWKXPNNX91N53XKQ7M8AAJ6",
      "roomName": "salon",
      "roomType": "LIVING_ROOM"
    },
    {
      "id": "01HPWKVGYAFYBW71KQ84M0ZBR6",
      "roomName": "pokój1",
      "roomType": "STANDARD"
    },
    {
      "id": "01HPWKZB5K7CN6X90N0X2F95K4",
      "roomName": "pokój2",
      "roomType": "STANDARD"
    }
  ]
}