import { Entity, Column, PrimaryColumn, Index, CreateDateColumn } from 'typeorm';

@Entity('domain_event_journal')
@Index(
  'idx_journal_aggregate_event',
  ['module', 'aggregateType', 'aggregateId', 'aggregateVersion', 'eventIndex'],
  { unique: true },
)
export class DomainEventJournalEntity {
  @PrimaryColumn('uuid', { name: 'event_id' })
  eventId!: string;

  // commitPosition is sequential BIGINT, generated by DB sequence
  @Column({ name: 'commit_position', type: 'bigint', generated: 'increment', unique: true })
  commitPosition!: number;

  @Column({ name: 'event_type', length: 255 })
  eventType!: string;

  @Column({ name: 'event_version', type: 'int' })
  eventVersion!: number;

  @Column({ length: 50 })
  module!: string;

  @Column({ name: 'aggregate_type', length: 100 })
  aggregateType!: string;

  @Column({ name: 'aggregate_id', type: 'uuid' })
  aggregateId!: string;

  @Column({ name: 'aggregate_version', type: 'int' })
  aggregateVersion!: number;

  @Column({ name: 'event_index', type: 'int' })
  eventIndex!: number;

  @Column({ name: 'occurred_at', type: 'timestamp' })
  occurredAt!: Date;

  @CreateDateColumn({ name: 'committed_at', type: 'timestamp' })
  committedAt!: Date;

  @Column({ name: 'actor_id', type: 'uuid', nullable: true })
  actorId!: string | null;

  @Column({ name: 'command_id', type: 'uuid' })
  commandId!: string;

  @Column({ name: 'correlation_id', type: 'uuid' })
  correlationId!: string;

  @Column({ name: 'causation_id', type: 'uuid', nullable: true })
  causationId!: string | null;

  @Column({ name: 'payload_json', type: 'text' })
  payloadJson!: string;
}
